spring.application.name=eureka

server.port=8761

#se evita que eureka se registre a si misma
eureka.client.register-with-eureka=false
#Valida si las instancias siguen activas
eureka.client.fetch-registry=false
#hace que el server prefiera las direcciones ip
eureka.instance.prefer-ip-address=true